branch-defaults:
  default:
    environment: Wipo-backend-env
deploy:
  artifact: build/libs/wipo-0.0.1-SNAPSHOT.jar
global:
  application_name: wipo-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
