name: CI/CD

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v3
         
         - uses: actions/setup-java@v3
           with:
                distribution: 'zulu'
                java-version: '17'
         - name: Grant execute permission for gradlew
           run: chmod +x gradlew
           
         - name: Build with gradlew
           env:
               DB_URL: ${{ secrets.DB_URL }}
               DB_USERNAME: ${{ secrets.DB_USERNAME }}
               DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
               JWT_SECRET: ${{ secrets.JWT_SECRET }}
               KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
               KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL }}
               GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
               NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
               NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
               NAVER_REDIRECT_URL: ${{ secrets.NAVER_REDIRECT_URL }}
           run: ./gradlew clean build -PdbUrl=$DB_URL -PdbUsername=$DB_USERNAME -PdbPassword=$DB_PASSWORD \
                -PjwtSecret=$JWT_SECRET -PkakaoClientId=$KAKAO_CLIENT_ID -PkakaoRedirectUrl=$KAKAO_REDIRECT_URL -PgoogleClientId=$GOOGLE_CLIENT_ID \
                -PnaverClientId=$NAVER_CLIENT_ID -PnaverSecret=$NAVER_SECRET -PnaverRedirectUrl=$NAVER_REDIRECT_URL
           
         - name: Get current time
           uses: josStorer/get-current-time@v2.0.2
           id: current-time
           with:
                format: YYYY-MM-DDTHH-mm-ss
                utcOffset: "+09:00"
                
         - name: Set artifact path
           run: |
                artifact=$(ls ./build/libs/*.jar)
                echo "artifact=$artifact" >> $GITHUB_ENV

           
         - name: Beanstalk Deploy
           uses: einaregilsson/beanstalk-deploy@v20
           with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                application_name: wipo-back
                environment_name: wipo-back-env
                version_label: github-action-${{steps.current-time.outputs.formattedTime}}
                region: ap-northeast-2
                deployment_package: ${{env.artifact}}