name: CI/CD3

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v3
         
         - uses: actions/setup-java@v3
           with:
                distribution: 'zulu'
                java-version: '17'
         - name: Get Public IP
           id: ip
           uses: haythem/public-ip@v1.3

         - name: Print Public IP
           run: |
                echo ${{ steps.ip.outputs.ipv4 }}
                
         - name: Grant execute permission for gradlew
           run: chmod +x gradlew
           
         - name: Create application.properties
           run: |
                echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties  
           
         - name: Debug application.properties
           run: cat src/main/resources/application.properties
           
         - name: Build with gradlew
           run: |
                ./gradlew clean build
           
         - name: Get current time
           uses: josStorer/get-current-time@v2.0.2
           id: current-time
           with:
                format: YYYY-MM-DDTHH-mm-ss
                utcOffset: "+09:00"
                
         - name: Set artifact path
           run: |
                artifact=$(ls ./build/libs/*.jar)
                echo "artifact=$artifact" >> $GITHUB_ENV

           
         - name:  Deploy to EC2
           uses: appleboy/scp-action@v0.2.1
           with:
                host: ec2-52-78-191-119.ap-northeast-2.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY }}
                source: build/libs/app.jar
                target: /home/ec2-user/app.jar
                
          - name: Restart Application
            uses: appleboy/ssh-action@v0.1.3
            with:
                host: ec2-52-78-191-119.ap-northeast-2.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  pkill -f 'java -jar' || true
                  nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &