name: SSH Test Workflow

on:
  push:
    branches:
      - main # 테스트를 main 브랜치로 푸시할 때 실행됩니다.

jobs:
  ssh-test:
    runs-on: ubuntu-latest # GitHub Actions의 실행 환경 (Ubuntu)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # 코드 체크아웃 (필요시)

      - name: Debug SSH Connection with RSA
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ec2-52-78-191-119.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # GitHub Secrets에 저장된 SSH 개인 키
          cipher: "aes256-ctr"            # RSA 암호화 알고리즘 사용
          debug: true                    # 디버그 모드 활성화
          script: |
            echo "Force RSA Test - SSH Connection Successful!"
            whoami                       # 현재 사용자 확인
            hostname                     # 서버 호스트명 확인
